# When a new pull request is made to main, this action ensures the site builds successfully,
# without actually deploying.

name: Test Build

on:
  pull_request:
    branches:
      - main
  # used to run action manually via the UI
  workflow_dispatch:

jobs:
  test-build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
